//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding4Fun.VisualStudio.TextTemplating.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Coding4Fun.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coding4Fun.VisualStudio.TextTemplating.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem loading the assembly &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This code was generated by a tool. 的本地化字符串。
        /// </summary>
        internal static string AutoGenCommentLine1 {
            get {
                return ResourceManager.GetString("AutoGenCommentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime Version: {0} 的本地化字符串。
        /// </summary>
        internal static string AutoGenCommentLine2 {
            get {
                return ResourceManager.GetString("AutoGenCommentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes to this file may cause incorrect behavior and will be lost if 的本地化字符串。
        /// </summary>
        internal static string AutoGenCommentLine3 {
            get {
                return ResourceManager.GetString("AutoGenCommentLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the code is regenerated. 的本地化字符串。
        /// </summary>
        internal static string AutoGenCommentLine4 {
            get {
                return ResourceManager.GetString("AutoGenCommentLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load base class &apos;{0}&apos; from which Transformation class inherits. 的本地化字符串。
        /// </summary>
        internal static string BaseClassNotFound {
            get {
                return ResourceManager.GetString("BaseClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading the include file &apos;{0}&apos; returned a null or empty string. The transformation will not be run.  的本地化字符串。
        /// </summary>
        internal static string BlankIncludeFile {
            get {
                return ResourceManager.GetString("BlankIncludeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem creating and initializing the processor for a directive named &apos;{1}&apos;. The type of the processor is {0}. The transformation will not be run.  的本地化字符串。
        /// </summary>
        internal static string CannotInitializeProcessor {
            get {
                return ResourceManager.GetString("CannotInitializeProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to resolve a value for the requires parameter &apos;{0}&apos; for directive &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotResolveRequiresParameter {
            get {
                return ResourceManager.GetString("CannotResolveRequiresParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiling transformation:  的本地化字符串。
        /// </summary>
        internal static string CompilerErrorPrepend {
            get {
                return ResourceManager.GetString("CompilerErrorPrepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown while trying to compile the transformation code. 的本地化字符串。
        /// </summary>
        internal static string CompilerErrors {
            get {
                return ResourceManager.GetString("CompilerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} 2.0 and {0} 3.5 compilers are no longer supported. Templates will always be compiled with the version 4 compiler instead of &apos;{1}&apos; as specified. 的本地化字符串。
        /// </summary>
        internal static string CompilerVersionNotSupported {
            get {
                return ResourceManager.GetString("CompilerVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; directive did not provide required argument &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DirectiveMissingArgument {
            get {
                return ResourceManager.GetString("DirectiveMissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directive &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string DirectiveNotSupported {
            get {
                return ResourceManager.GetString("DirectiveNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; already exists in the directive. The duplicate parameter will be ignored. 的本地化字符串。
        /// </summary>
        internal static string DuplicateDirectiveParameter {
            get {
                return ResourceManager.GetString("DuplicateDirectiveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding.GetEncoding(int) failed for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EncodingIntegerFailed {
            get {
                return ResourceManager.GetString("EncodingIntegerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding.GetEncoding(string) failed for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EncodingStringFailed {
            get {
                return ResourceManager.GetString("EncodingStringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error generating the transformation class. The process cannot continue.  的本地化字符串。
        /// </summary>
        internal static string ErrorGeneratingTranformationClass {
            get {
                return ResourceManager.GetString("ErrorGeneratingTranformationClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors were generated when initializing the transformation object. The transformation will not be run.  的本地化字符串。
        /// </summary>
        internal static string ErrorInitializingTransformationObject {
            get {
                return ResourceManager.GetString("ErrorInitializingTransformationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error loading the include file &apos;{0}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ErrorLoadingIncludeFile {
            get {
                return ResourceManager.GetString("ErrorLoadingIncludeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErrorGeneratingOutput 的本地化字符串。
        /// </summary>
        internal static string ErrorOutput {
            get {
                return ResourceManager.GetString("ErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  The following Exception was thrown:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Exception was thrown while trying to get the output from the processor named &apos;{0}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ExceptionGettingProcessorOutput {
            get {
                return ResourceManager.GetString("ExceptionGettingProcessorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Exception was thrown while trying to get the namespace imports and assembly references for processing the run from a directive processor named &apos;{0}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ExceptionGettingReferencesFromDP {
            get {
                return ResourceManager.GetString("ExceptionGettingReferencesFromDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown by the host when trying to get the StandardImports and StandardAssemblyReferences. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ExceptionGettingStandardReferences {
            get {
                return ResourceManager.GetString("ExceptionGettingStandardReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not instantiate a TextTransformation object from the compiled assembly. 的本地化字符串。
        /// </summary>
        internal static string ExceptionInstantiatingTransformationObject {
            get {
                return ResourceManager.GetString("ExceptionInstantiatingTransformationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Exception was thrown while processing a directive named &apos;{0}&apos;. The transformation will not be run.  的本地化字符串。
        /// </summary>
        internal static string ExceptionProcessingDirective {
            get {
                return ResourceManager.GetString("ExceptionProcessingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Exception was thrown while processing the template.  的本地化字符串。
        /// </summary>
        internal static string ExceptionProcessingTemplate {
            get {
                return ResourceManager.GetString("ExceptionProcessingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host threw an exception while trying to resolve the assembly reference &apos;{0}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ExceptionResolvingAssembly {
            get {
                return ResourceManager.GetString("ExceptionResolvingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown while running the TransformText() method.  的本地化字符串。
        /// </summary>
        internal static string ExceptionRunningTransformText {
            get {
                return ResourceManager.GetString("ExceptionRunningTransformText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown by the host while trying to set the extension. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSettingExtension {
            get {
                return ResourceManager.GetString("ExceptionSettingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown while trying to set the &apos;Host&apos; property on the {0}.  的本地化字符串。
        /// </summary>
        internal static string ExceptionSettingHost {
            get {
                return ResourceManager.GetString("ExceptionSettingHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception was thrown while trying to set the &apos;Session&apos; property on the {0}.  的本地化字符串。
        /// </summary>
        internal static string ExceptionSettingSession {
            get {
                return ResourceManager.GetString("ExceptionSettingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Exception was thrown while running the transformation code. The process cannot continue.  的本地化字符串。
        /// </summary>
        internal static string ExceptionWhileRunningCode {
            get {
                return ResourceManager.GetString("ExceptionWhileRunningCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An expression block evaluated as Null 的本地化字符串。
        /// </summary>
        internal static string ExpressionBlockNull {
            get {
                return ResourceManager.GetString("ExpressionBlockNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file {0} was not found whilst processing a directive named &apos;{1}&apos;.  的本地化字符串。
        /// </summary>
        internal static string FileNotFoundExceptionProcessingDirective {
            get {
                return ResourceManager.GetString("FileNotFoundExceptionProcessingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class code can only be retrieved after FinishProcessingRun() is called 的本地化字符串。
        /// </summary>
        internal static string GetClassCodeCallError {
            get {
                return ResourceManager.GetString("GetClassCodeCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imports can only be retrieved after FinishProcessingRun() is called 的本地化字符串。
        /// </summary>
        internal static string GetImportsCallError {
            get {
                return ResourceManager.GetString("GetImportsCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 References can only be retrieved after FinishProcessingRun() is called 的本地化字符串。
        /// </summary>
        internal static string GetReferencesCallError {
            get {
                return ResourceManager.GetString("GetReferencesCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A &apos;Host&apos; property was not found despite the template directive setting hostspecific=&apos;truefrombase&apos;. Check that the base class &apos;{0}&apos; has a &apos;Host&apos; property. 的本地化字符串。
        /// </summary>
        internal static string HostPropertyNotFound {
            get {
                return ResourceManager.GetString("HostPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; of the directive processor named &apos;{1}&apos; does not implement Coding4Fun.VisualStudio.TextTemplating.IDirectiveProcessor. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string IncorrectDPType {
            get {
                return ResourceManager.GetString("IncorrectDPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid base class was specified for the Transformation class. The base class must implement the same members as Coding4Fun.VisualStudio.TextTemplating.TextTransformation. 的本地化字符串。
        /// </summary>
        internal static string InvalidBaseClass {
            get {
                return ResourceManager.GetString("InvalidBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The compiler option is invalid: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCompilerOption {
            get {
                return ResourceManager.GetString("InvalidCompilerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid culture was specified in the &apos;template&apos; directive. The culture must be in the &quot;xx-XX&quot; format. The invariant culture will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid debug value &apos;{0}&apos; was specified in the template directive. The debug value must be either &quot;true&quot; or &quot;false&quot;. The default of &quot;false&quot; will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidDebugParam {
            get {
                return ResourceManager.GetString("InvalidDebugParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directive arguments should be of form &apos;name=value&apos;: {0}. 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectiveArgumentFormat {
            get {
                return ResourceManager.GetString("InvalidDirectiveArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid HostSpecific value &apos;{0}&apos; was specified in the template directive. The HostSpecific value must be either &quot;true&quot;, &quot;false&quot; or &quot;truefrombase&quot;. The default of &quot;false&quot; will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidHostSpecificParam {
            get {
                return ResourceManager.GetString("InvalidHostSpecificParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid language &apos;{0}&apos; was specified in the &apos;template&apos; directive. The language must be either &quot;C#&quot; or &quot;VB&quot;. The default value of &quot;C#&quot; will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid linePragmas value &apos;{0}&apos; was specified in the template directive. The value must be either &quot;true&quot; or &quot;false&quot;. The default of &quot;true&quot; will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidLinePragmasParam {
            get {
                return ResourceManager.GetString("InvalidLinePragmasParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A neutral culture was specified in the &apos;template&apos; directive. A specific culture must be provided. The invariant culture will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidNeutralCulture {
            get {
                return ResourceManager.GetString("InvalidNeutralCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An invalid visibility &apos;{0}&apos; was specified in the &apos;template&apos; directive. The visibility must be either &apos;internal&apos; or &apos;public&apos;. The default value of &apos;public&apos; will be used. 的本地化字符串。
        /// </summary>
        internal static string InvalidVisibility {
            get {
                return ResourceManager.GetString("InvalidVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A template that specifies hostspecific=&apos;truefrombase&apos; must also specify a base template with the &apos;inherits&apos; parameter to the template directive. 的本地化字符串。
        /// </summary>
        internal static string MissingBaseClass {
            get {
                return ResourceManager.GetString("MissingBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple output directives were found in the template. All but the first one will be ignored. 的本地化字符串。
        /// </summary>
        internal static string MultipleOutputDirectives {
            get {
                return ResourceManager.GetString("MultipleOutputDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple template directives were found in the template. All but the first one will be ignored. Multiple parameters to the template directive should be specified within one template directive. 的本地化字符串。
        /// </summary>
        internal static string MultipleTemplateDirectives {
            get {
                return ResourceManager.GetString("MultipleTemplateDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem getting an AppDomain to run the transformation from the host. The process cannot continue.  的本地化字符串。
        /// </summary>
        internal static string NoAppDomain {
            get {
                return ResourceManager.GetString("NoAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No processor was specified for a directive named &apos;{0}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string NoProcessorForDirective {
            get {
                return ResourceManager.GetString("NoProcessorForDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A processor named &apos;{0}&apos; could not be found for the directive named &apos;{1}&apos;. The transformation will not be run.  的本地化字符串。
        /// </summary>
        internal static string NoProcessorTypeForDirective {
            get {
                return ResourceManager.GetString("NoProcessorTypeForDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A required parameter &apos;{0}&apos; for the directive &apos;{1}&apos; was not found. The directive will be ignored.  的本地化字符串。
        /// </summary>
        internal static string NotEnoughDirectiveParameters {
            get {
                return ResourceManager.GetString("NotEnoughDirectiveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{1}&apos; of the parameter &apos;{0}&apos; did not match the type of the data passed to the template. 的本地化字符串。
        /// </summary>
        internal static string ParameterDirectiveTypeMismatch {
            get {
                return ResourceManager.GetString("ParameterDirectiveTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessDirective() was called before StartProcessingRun(). Directive processing can only start after StartProcessingRun() is called.  的本地化字符串。
        /// </summary>
        internal static string ProcessDirectiveCallError {
            get {
                return ResourceManager.GetString("ProcessDirectiveCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The processor named &apos;{0}&apos; does not support the directive named &apos;{1}&apos;. The transformation will not be run. 的本地化字符串。
        /// </summary>
        internal static string ProcessorNotSupportDirective {
            get {
                return ResourceManager.GetString("ProcessorNotSupportDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The include directive for file &apos;{0}&apos; causes an infinite loop. The directive will not be processed. 的本地化字符串。
        /// </summary>
        internal static string RecursiveInclude {
            get {
                return ResourceManager.GetString("RecursiveInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marshaling Session or Host object to secondary AppDomain failed. Check that Host and all types in Session dictionary are Serializable or derive from MarshalByReferenceObject. 的本地化字符串。
        /// </summary>
        internal static string SessionHostMarshalError {
            get {
                return ResourceManager.GetString("SessionHostMarshalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host threw an exception from SetOutputEncoding(). 的本地化字符串。
        /// </summary>
        internal static string SetOutputEncodingFailed {
            get {
                return ResourceManager.GetString("SetOutputEncodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartProcessingRun() was called after directive processing was already started. 的本地化字符串。
        /// </summary>
        internal static string StartProcessingCallError {
            get {
                return ResourceManager.GetString("StartProcessingCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running transformation:  的本地化字符串。
        /// </summary>
        internal static string TransformationErrorPrepend {
            get {
                return ResourceManager.GetString("TransformationErrorPrepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected start or end tag was found within a block. Make sure that you did not mis-type a start or end tag, and that you do not have any nested blocks in the template. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedTag {
            get {
                return ResourceManager.GetString("UnexpectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to specify unsupported {1} value &apos;{0}&apos; for directive {2} 的本地化字符串。
        /// </summary>
        internal static string UnsupportedArgumentValue {
            get {
                return ResourceManager.GetString("UnsupportedArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {0} cannot appear after the first class feature in the template. Only boilerplate, expressions and other class features are allowed after the first class feature block. 的本地化字符串。
        /// </summary>
        internal static string WrongBlockSequence {
            get {
                return ResourceManager.GetString("WrongBlockSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A directive was specified in the wrong format. The transformation will not be run. Please specify the directive in the format &lt;#@ name [parameterName=&quot;parameterValue&quot;]*  #&gt; 的本地化字符串。
        /// </summary>
        internal static string WrongDirectiveFormat {
            get {
                return ResourceManager.GetString("WrongDirectiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A template containing a class feature must end with a class feature. 的本地化字符串。
        /// </summary>
        internal static string WrongFinalBlockType {
            get {
                return ResourceManager.GetString("WrongFinalBlockType", resourceCulture);
            }
        }
    }
}
